defaults:
  - _self_

run_name_: inference_proteinae

ckpt_path: checkpoints
ckpt_name: ae_r1_d8_v1.ckpt

self_cond: True
dt: 0.05

sampling_bbflow:
  sampling_mode: vf  # Options are: vf (plain fow matching) or sc (using score, where parameters below matter)
  sc_scale_noise: 0.4
  sc_scale_score: 1.0
  gt_mode: "1/t"  # us, tan, or 1/t
  gt_p: 1.0  # float
  gt_clamp_val: null  # 10.0 float or null

schedule:
  schedule_mode: log
  schedule_p: 2.0

ca_only: True
ae_mode: autoencode
inv_folding: False

fold_cond: False
guidance_weight: 1.0
autoguidance_ratio: 1.0
autoguidance_ckpt_path: null

seed: 43
nsamples_per_len: 1
max_nsamples: 1
compute_designability: False
compute_fid: False
designability_seqs_per_struct: 8