#!/usr/bin/env bash
#SBATCH --job-name=latentde_sim
#SBATCH --gpus=1
#SBATCH --cpus-per-task=20
#SBATCH --mem-per-cpu=3G
#SBATCH --time=12:00:00
#SBATCH --output=%x_%j.log
#SBATCH --error=%x_%j.err

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

DATASET="avGFP"
CSV_FILE=""
DECODER="rnn"
DEVICES=""
EXPECTED_KL="25"
BATCH_SIZE="32"
EPOCHS="130"
SEED="42"
PREFIX="smooth"
INTERP_WEIGHT="0.01"
LATENT_WEIGHT="0.01"
RUN_METHODS="ess,tess"
TRUST_RADIUS="4.0"

show_help() {
  cat << 'EOF'
Usage: sbatch run_full_simulation_uv.sh [options]
   or: bash run_full_simulation_uv.sh [options]

SLURM Directives:
  - Job runs on 1 GPU and 20 CPU cores
  - Allocates up to 60GB memory
  - 12-hour time limit
  - Logs: <jobname>_<jobid>.{log,err}

The script defaults to a single GPU unless --devices is set explicitly.

Defaults are usable with no args.

Options:
  --dataset NAME           Dataset under preprocessed_data/ (default: avGFP)
  --csv PATH               Explicit CSV path (overrides --dataset)
  --decoder TYPE           rnn|cnn (default: rnn)
  --devices IDS            CUDA ids, e.g. 0 (default: 0)
  --expected-kl FLOAT      KL target (default: 25)
  --batch-size INT         Batch size (default: 32)
  --epochs INT             Training epochs (default: 130)
  --seed INT               Seed (default: 42)
  --prefix STR             Prefix for ckpts/results (default: smooth)
  --interp-weight FLOAT    Smoothness interpolation weight (default: 0.01)
  --latent-weight FLOAT    Smoothness latent norm weight (default: 0.01)
  --run-methods STR        ess,tess|ess|tess|none (default: ess,tess)
  --trust-radius FLOAT     TESS trust radius (default: 4.0)
  -h, --help               Show help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dataset) DATASET="$2"; shift 2 ;;
    --csv) CSV_FILE="$2"; shift 2 ;;
    --decoder) DECODER="$2"; shift 2 ;;
    --devices) DEVICES="$2"; shift 2 ;;
    --expected-kl) EXPECTED_KL="$2"; shift 2 ;;
    --batch-size) BATCH_SIZE="$2"; shift 2 ;;
    --epochs) EPOCHS="$2"; shift 2 ;;
    --seed) SEED="$2"; shift 2 ;;
    --prefix) PREFIX="$2"; shift 2 ;;
    --interp-weight) INTERP_WEIGHT="$2"; shift 2 ;;
    --latent-weight) LATENT_WEIGHT="$2"; shift 2 ;;
    --run-methods) RUN_METHODS="$2"; shift 2 ;;
    --trust-radius) TRUST_RADIUS="$2"; shift 2 ;;
    -h|--help) show_help; exit 0 ;;
    *) echo "Unknown option: $1"; show_help; exit 1 ;;
  esac
done

if [[ "$DECODER" != "rnn" && "$DECODER" != "cnn" ]]; then
  echo "Error: --decoder must be rnn or cnn"
  exit 1
fi

if [[ -z "$CSV_FILE" ]]; then
  CSV_FILE="$ROOT_DIR/preprocessed_data/${DATASET}/${DATASET}.csv"
fi
if [[ ! -f "$CSV_FILE" ]]; then
  echo "Error: CSV not found: $CSV_FILE"
  exit 1
fi

if [[ ! -f "$ROOT_DIR/.project-root" ]]; then
  touch "$ROOT_DIR/.project-root"
fi

if ! command -v uv >/dev/null 2>&1; then
  echo "Error: uv not found. Install uv and rerun."
  exit 1
fi

if [[ ! -x "$ROOT_DIR/.venv/bin/python" ]]; then
  echo "[setup] creating .venv"
  uv venv --python 3.10 "$ROOT_DIR/.venv"
fi

if [[ -z "$DEVICES" ]]; then
  DEVICES="0"
fi

MARKER="$ROOT_DIR/.venv/.latentde_deps_ok"
if [[ ! -f "$MARKER" ]]; then
  echo "[setup] installing dependencies"
  uv pip install --python "$ROOT_DIR/.venv/bin/python" \
    --extra-index-url https://download.pytorch.org/whl/cu116 \
    torch==1.13.1+cu116 \
    lightning==2.1.2 \
    pytorch-lightning==2.1.2 \
    transformers==4.33.3 \
    scikit-learn==1.3.2 \
    tape-proteins==0.5 \
    matplotlib==3.8.2 \
    pandas==2.1.4 \
    rootutils==1.0.7 \
    seaborn==0.13.0 \
    wandb==0.16.1 \
    tabulate==0.9.0 \
    polyleven==0.8 \
    rich==13.7.0
  touch "$MARKER"
fi

BASE_CFG="$ROOT_DIR/scripts/configs/${DECODER}_template.py"
AUTO_CFG="$ROOT_DIR/scripts/configs/_auto_${DECODER}_smooth_sim.py"
cp "$BASE_CFG" "$AUTO_CFG"
cat >> "$AUTO_CFG" <<EOF

# Auto-generated by run_full_simulation_uv.sh
model_kwargs["interp_weight"] = ${INTERP_WEIGHT}
model_kwargs["latent_weight"] = ${LATENT_WEIGHT}
data_kwargs["num_workers"] = 2
EOF

if [[ "$DEVICES" != "-1" && "$DEVICES" == *","* ]]; then
  export NCCL_ASYNC_ERROR_HANDLING=1
  export NCCL_IB_DISABLE=${NCCL_IB_DISABLE:-1}
  export NCCL_P2P_DISABLE=${NCCL_P2P_DISABLE:-1}
  export NCCL_DEBUG=${NCCL_DEBUG:-WARN}
fi
export WANDB_MODE=${WANDB_MODE:-offline}
export PYTORCH_CUDA_ALLOC_CONF=${PYTORCH_CUDA_ALLOC_CONF:-max_split_size_mb:64}

FIRST_GPU="${DEVICES%%,*}"
if [[ "$FIRST_GPU" != "-1" ]]; then
  echo "[setup] pre-caching ESM2 on GPU ${FIRST_GPU}"
  CUDA_VISIBLE_DEVICES="$FIRST_GPU" uv run --python "$ROOT_DIR/.venv/bin/python" -- python -c "from transformers import AutoTokenizer, EsmModel; AutoTokenizer.from_pretrained('facebook/esm2_t30_150M_UR50D'); EsmModel.from_pretrained('facebook/esm2_t30_150M_UR50D'); print('esm2_cached')"
fi

echo "[train] starting training"
cd "$ROOT_DIR"
uv run --python "$ROOT_DIR/.venv/bin/python" scripts/train_vae.py "$AUTO_CFG" \
  --csv_file="$CSV_FILE" \
  --expected_kl="$EXPECTED_KL" \
  --batch_size="$BATCH_SIZE" \
  --devices="$DEVICES" \
  --epochs="$EPOCHS" \
  --seed="$SEED" \
  --prefix="$PREFIX"

DATA_NAME="$(basename "$CSV_FILE" .csv)"
CKPT_DIR="$ROOT_DIR/exps/ckpts/${DATA_NAME}"
if [[ ! -d "$CKPT_DIR" ]]; then
  echo "Error: checkpoint directory not found: $CKPT_DIR"
  exit 2
fi

BEST_CKPT="$(ls -1t "$CKPT_DIR"/*.ckpt 2>/dev/null | head -n 1 || true)"
if [[ -z "$BEST_CKPT" ]]; then
  echo "Error: no checkpoint produced in $CKPT_DIR"
  exit 2
fi

echo "[check] running latent-space fail-safe checks on: $BEST_CKPT"
CHECK_DEVICE="cuda"
if [[ "$DEVICES" == "-1" ]]; then
  CHECK_DEVICE="cpu"
fi
uv run --python "$ROOT_DIR/.venv/bin/python" scripts/check_latent_quality.py \
  --ckpt "$BEST_CKPT" \
  --csv "$CSV_FILE" \
  --model_type "$DECODER" \
  --device "$CHECK_DEVICE"

RESULTS_DIR="$ROOT_DIR/exps/results"
mkdir -p "$RESULTS_DIR"

if [[ "$RUN_METHODS" == *"ess"* ]]; then
  echo "[sim] running ESS"
  uv run --python "$ROOT_DIR/.venv/bin/python" optimize.py \
    --method ess \
    --ckpt "$BEST_CKPT" \
    --model_type "$DECODER" \
    --dataset "$DATASET" \
    --wt_csv "$CSV_FILE" \
    --output "$RESULTS_DIR/${DATASET}_${PREFIX}_ess.csv" \
    --device "$CHECK_DEVICE"
fi

if [[ "$RUN_METHODS" == *"tess"* ]]; then
  echo "[sim] running TESS"
  uv run --python "$ROOT_DIR/.venv/bin/python" optimize.py \
    --method tess \
    --ckpt "$BEST_CKPT" \
    --model_type "$DECODER" \
    --dataset "$DATASET" \
    --wt_csv "$CSV_FILE" \
    --output "$RESULTS_DIR/${DATASET}_${PREFIX}_tess.csv" \
    --trust_radius "$TRUST_RADIUS" \
    --device "$CHECK_DEVICE"
fi

echo "[done] full simulation pipeline complete"
echo "  checkpoint: $BEST_CKPT"
echo "  results:    $RESULTS_DIR"
